### ISSUE TITLE
[AIRFLOW-2549] GCP DataProc Workflow Template operators report success when jobs fail

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow#117]
Hello,

Here is an ticket related to GCP on Jira:
https://issues.apache.org/jira/browse/AIRFLOW-2549

Love

**Comment by nuclearpinguin** [comment]
Could not replicate the problem.

Steps I took:
- create Dataproc workflow `tomek-flow` with two jobs: 
   - `hadoop_job` - supposed to fail
   - `pig_job` - supposed to success
- create example DAG with `DataprocWorkflowTemplateInstantiateOperator` to instantiate `tome-flow`
- wait for output:
```sh
[2019-07-18 08:38:25,294] {taskinstance.py:614} INFO - Dependencies all met for <TaskInstance: example_gcp_dataproc_template.instantiate_task 2019-01-01T00:00:00+00:00 [None]>
[2019-07-18 08:38:25,300] {taskinstance.py:614} INFO - Dependencies all met for <TaskInstance: example_gcp_dataproc_template.instantiate_task 2019-01-01T00:00:00+00:00 [None]>
[2019-07-18 08:38:25,300] {taskinstance.py:832} INFO -
--------------------------------------------------------------------------------
[2019-07-18 08:38:25,300] {taskinstance.py:833} INFO - Starting attempt 1 of 1
[2019-07-18 08:38:25,300] {taskinstance.py:834} INFO -
--------------------------------------------------------------------------------
[2019-07-18 08:38:25,301] {taskinstance.py:853} INFO - Executing <Task(DataprocWorkflowTemplateInstantiateOperator): instantiate_task> on 2019-01-01T00:00:00+00:00
[2019-07-18 08:38:25,318] {dataproc_operator.py:1098} INFO - Instantiating Template: tomek-flow
[2019-07-18 08:38:25,318] {gcp_api_base_hook.py:98} INFO - Getting connection using `google.auth.default()` since no key file is defined for hook.
[2019-07-18 08:38:25,325] {discovery.py:272} INFO - URL being requested: GET https://www.googleapis.com/discovery/v1/apis/dataproc/v1beta2/rest
[2019-07-18 08:38:25,644] {discovery.py:873} INFO - URL being requested: POST https://dataproc.googleapis.com/v1beta2/projects/polidea-airflow/regions/global/workflowTemplates/tomek-flow:instantiate?alt=json
[2019-07-18 08:38:27,613] {gcp_api_base_hook.py:98} INFO - Getting connection using `google.auth.default()` since no key file is defined for hook.
[2019-07-18 08:38:27,622] {discovery.py:272} INFO - URL being requested: GET https://www.googleapis.com/discovery/v1/apis/dataproc/v1beta2/rest
[2019-07-18 08:38:27,900] {gcp_dataproc_hook.py:363} INFO - Waiting for Dataproc Operation projects/polidea-airflow/regions/global/operations/c0e2c4b0-1408-3976-a139-cb1b32782d1c to finish
[2019-07-18 08:38:37,879] {discovery.py:873} INFO - URL being requested: GET https://dataproc.googleapis.com/v1beta2/projects/polidea-airflow/regions/global/operations/c0e2c4b0-1408-3976-a139-cb1b32782d1c?alt=json
[2019-07-18 08:38:48,782] {discovery.py:873} INFO - URL being requested: GET https://dataproc.googleapis.com/v1beta2/projects/polidea-airflow/regions/global/operations/c0e2c4b0-1408-3976-a139-cb1b32782d1c?alt=json
[2019-07-18 08:38:59,586] {discovery.py:873} INFO - URL being requested: GET https://dataproc.googleapis.com/v1beta2/projects/polidea-airflow/regions/global/operations/c0e2c4b0-1408-3976-a139-cb1b32782d1c?alt=json
[2019-07-18 08:39:09,866] {discovery.py:873} INFO - URL being requested: GET https://dataproc.googleapis.com/v1beta2/projects/polidea-airflow/regions/global/operations/c0e2c4b0-1408-3976-a139-cb1b32782d1c?alt=json
[2019-07-18 08:39:20,153] {discovery.py:873} INFO - URL being requested: GET https://dataproc.googleapis.com/v1beta2/projects/polidea-airflow/regions/global/operations/c0e2c4b0-1408-3976-a139-cb1b32782d1c?alt=json
[2019-07-18 08:39:30,731] {discovery.py:873} INFO - URL being requested: GET https://dataproc.googleapis.com/v1beta2/projects/polidea-airflow/regions/global/operations/c0e2c4b0-1408-3976-a139-cb1b32782d1c?alt=json
[2019-07-18 08:39:41,195] {discovery.py:873} INFO - URL being requested: GET https://dataproc.googleapis.com/v1beta2/projects/polidea-airflow/regions/global/operations/c0e2c4b0-1408-3976-a139-cb1b32782d1c?alt=json
[2019-07-18 08:39:52,479] {discovery.py:873} INFO - URL being requested: GET https://dataproc.googleapis.com/v1beta2/projects/polidea-airflow/regions/global/operations/c0e2c4b0-1408-3976-a139-cb1b32782d1c?alt=json
[2019-07-18 08:40:02,884] {discovery.py:873} INFO - URL being requested: GET https://dataproc.googleapis.com/v1beta2/projects/polidea-airflow/regions/global/operations/c0e2c4b0-1408-3976-a139-cb1b32782d1c?alt=json
[2019-07-18 08:40:13,142] {discovery.py:873} INFO - URL being requested: GET https://dataproc.googleapis.com/v1beta2/projects/polidea-airflow/regions/global/operations/c0e2c4b0-1408-3976-a139-cb1b32782d1c?alt=json
[2019-07-18 08:40:23,924] {discovery.py:873} INFO - URL being requested: GET https://dataproc.googleapis.com/v1beta2/projects/polidea-airflow/regions/global/operations/c0e2c4b0-1408-3976-a139-cb1b32782d1c?alt=json
[2019-07-18 08:40:34,642] {discovery.py:873} INFO - URL being requested: GET https://dataproc.googleapis.com/v1beta2/projects/polidea-airflow/regions/global/operations/c0e2c4b0-1408-3976-a139-cb1b32782d1c?alt=json
[2019-07-18 08:40:44,928] {discovery.py:873} INFO - URL being requested: GET https://dataproc.googleapis.com/v1beta2/projects/polidea-airflow/regions/global/operations/c0e2c4b0-1408-3976-a139-cb1b32782d1c?alt=json
[2019-07-18 08:40:45,209] {gcp_dataproc_hook.py:389} WARNING - Dataproc Operation projects/polidea-airflow/regions/global/operations/c0e2c4b0-1408-3976-a139-cb1b32782d1c failed with error: Step 'hadoop_job' (hadoop_job-a342p4tbavep6) failed
[2019-07-18 08:40:45,210] {taskinstance.py:1045} ERROR - Google Dataproc Operation projects/polidea-airflow/regions/global/operations/c0e2c4b0-1408-3976-a139-cb1b32782d1c failed: Step 'hadoop_job' (hadoop_job-a342p4tbavep6) failed
Traceback (most recent call last):
  File "/workspace/airflow/models/taskinstance.py", line 920, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/workspace/airflow/contrib/operators/dataproc_operator.py", line 66, in execute
    self.hook.wait(self.start())
  File "/workspace/airflow/contrib/hooks/gcp_dataproc_hook.py", line 497, in wait
    submitted.wait_for_done()
  File "/workspace/airflow/contrib/hooks/gcp_dataproc_hook.py", line 373, in wait_for_done
    if self._check_done():
  File "/workspace/airflow/contrib/hooks/gcp_dataproc_hook.py", line 390, in _check_done
    self._raise_error()
  File "/workspace/airflow/contrib/hooks/gcp_dataproc_hook.py", line 399, in _raise_error
    (self.operation_name, self.operation['error']['message']))
Exception: Google Dataproc Operation projects/polidea-airflow/regions/global/operations/c0e2c4b0-1408-3976-a139-cb1b32782d1c failed: Step 'hadoop_job' (hadoop_job-a342p4tbavep6) failed
[2019-07-18 08:40:45,232] {taskinstance.py:1076} INFO - Marking task as FAILED.
Traceback (most recent call last):
  File "/root/.virtualenvs/airflow36/bin/airflow", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/workspace/airflow/bin/airflow", line 32, in <module>
    args.func(args)
  File "/workspace/airflow/utils/cli.py", line 73, in wrapper
    return f(*args, **kwargs)
  File "/workspace/airflow/bin/cli.py", line 685, in test
    ti.run(ignore_task_deps=True, ignore_ti_state=True, test_mode=True)
  File "/workspace/airflow/utils/db.py", line 69, in wrapper
    return func(*args, **kwargs)
  File "/workspace/airflow/models/taskinstance.py", line 1007, in run
    session=session)
  File "/workspace/airflow/utils/db.py", line 65, in wrapper
    return func(*args, **kwargs)
  File "/workspace/airflow/models/taskinstance.py", line 920, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/workspace/airflow/contrib/operators/dataproc_operator.py", line 66, in execute
    self.hook.wait(self.start())
  File "/workspace/airflow/contrib/hooks/gcp_dataproc_hook.py", line 497, in wait
    submitted.wait_for_done()
  File "/workspace/airflow/contrib/hooks/gcp_dataproc_hook.py", line 373, in wait_for_done
    if self._check_done():
  File "/workspace/airflow/contrib/hooks/gcp_dataproc_hook.py", line 390, in _check_done
    self._raise_error()
  File "/workspace/airflow/contrib/hooks/gcp_dataproc_hook.py", line 399, in _raise_error
    (self.operation_name, self.operation['error']['message']))
Exception: Google Dataproc Operation projects/polidea-airflow/regions/global/operations/c0e2c4b0-1408-3976-a139-cb1b32782d1c failed: Step 'hadoop_job' (hadoop_job-a342p4tbavep6) failed
```

Last line contains information about the workflow's failure.

**Comment by mik-laj** [comment]
Can you write this information in Jira and call me? I will then close the application.
