### ISSUE TITLE
Make BigQueryCreateEmptyDatasetOperator idempotent

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow#257]
When I tried to rerun task, I receive a error:
```
googleapiclient.errors.HttpError: <HttpError 409 when requesting https://www.googleapis.com/bigquery/v2/projects/polidea-airflow/datasets?alt=json returned "Already Exists: Dataset polidea-airflow:test_dataset">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/opt/airflow/airflow/bin/airflow", line 36, in <module>
    args.func(args)
  File "/opt/airflow/airflow/utils/cli.py", line 73, in wrapper
    return f(*args, **kwargs)
  File "/opt/airflow/airflow/bin/cli.py", line 709, in test
    ti.run(ignore_task_deps=True, ignore_ti_state=True, test_mode=True)
  File "/opt/airflow/airflow/utils/db.py", line 69, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/airflow/models/taskinstance.py", line 999, in run
    session=session)
  File "/opt/airflow/airflow/utils/db.py", line 65, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/airflow/models/taskinstance.py", line 912, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/airflow/contrib/operators/bigquery_operator.py", line 789, in execute
    dataset_reference=self.dataset_reference)
  File "/opt/airflow/airflow/contrib/hooks/bigquery_hook.py", line 1680, in create_empty_dataset
    'BigQuery job failed. Error was: {}'.format(err.content)
airflow.exceptions.AirflowException: BigQuery job failed. Error was: b'{\n  "error": {\n    "code": 409,\n    "message": "Already Exists: Dataset polidea-airflow:test_dataset",\n    "errors": [\n      {\n        "message": "Already Exists: Dataset polidea-airflow:test_dataset",\n        "domain": "global",\n        "reason": "duplicate"\n      }\n    ],\n    "status": "ALREADY_EXISTS"\n  }\n}\n'
```

**Comment by nuclearpinguin** [comment]
Closed via https://github.com/apache/airflow/pull/6470
