### ISSUE TITLE
Why TestStringifiedDAGs works?

### ISSUE THREAD

**Issue by nuclearpinguin** [PolideaInternal/airflow#345]
So, this class tests serialisation and deserialisation of DAGs. But... the test DAGs include:
https://github.com/apache/airflow/blob/b2e06d0edcdbcfbe65e5135554bd45b3e2d76cd0/tests/dags/test_dag_serialization.py#L65-L84

As you know, those DAGs has been moved to core and renamed. I dunno why this is not failing on CI. There is a subprocess which I think may be killed by test timeout (?) and in case of nose the test will success:
```
root@6ac5c8d515b1:/opt/airflow# nosetests tests/dags
/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
/opt/airflow/airflow/contrib/operators/qubole_operator.py:172: PendingDeprecationWarning: Invalid arguments were passed to QuboleOperator (task_id: hive_s3_location). Support for passing such arguments will be dropped in Airflow 2.0. Invalid arguments were:
*args: ()
**kwargs: {'notfiy': True}
  super().__init__(*args, **filtered_base_kwargs)
/opt/airflow/airflow/contrib/operators/qubole_operator.py:172: PendingDeprecationWarning: Invalid arguments were passed to QuboleOperator (task_id: db_import). Support for passing such arguments will be dropped in Airflow 2.0. Invalid arguments were:
*args: ()
**kwargs: {'db_parallelism': 2}
  super().__init__(*args, **filtered_base_kwargs)
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/airflow/tests/dags/test_dag_serialization.py", line 210, in serialize_subprocess
    dags = collect_dags()
  File "/opt/airflow/tests/dags/test_dag_serialization.py", line 204, in collect_dags
    dags.update(make_example_dags(contrib_example_dags, CONTRIB_EXAMPLE_DAGS))
  File "/opt/airflow/tests/dags/test_dag_serialization.py", line 156, in make_example_dags
    return {k: dagbag.dags[k] for k in dag_ids}
  File "/opt/airflow/tests/dags/test_dag_serialization.py", line 156, in <dictcomp>
    return {k: dagbag.dags[k] for k in dag_ids}
KeyError: 'example_gcp_bigtable_operators'
^C
----------------------------------------------------------------------
Ran 1 test in 9.148s

OK
```

**Comment by nuclearpinguin** [comment]
Any ideas @mik-laj @potiuk ?

**Comment by nuclearpinguin** [comment]
Seems to be solved:
https://apache-airflow.slack.com/archives/CLV191AKH/p1569514621011300
