### ISSUE TITLE
Check if CloudVisionAnnotateImageOperator return object has still the same structure

### ISSUE THREAD

**Issue by turbaszek** [PolideaInternal/airflow#559]
```
[2019-12-30 16:44:16,808] {taskinstance.py:859} INFO - Executing <Task(BashOperator): annotate_image_result> on 2019-12-29T00:00:00+00:00
[2019-12-30 16:44:16,811] {standard_task_runner.py:53} INFO - Started process 9474 to run task
[2019-12-30 16:44:16,862] {logging_mixin.py:89} INFO - [2019-12-30 16:44:16,861] {dagbag.py:411} INFO - Filling up the DagBag from /opt/airflow/airflow/providers/google/cloud/example_dags/example_vision.py
[2019-12-30 16:44:16,924] {logging_mixin.py:89} INFO - Running <TaskInstance: example_gcp_vision_annotate_image.annotate_image_result 2019-12-29T00:00:00+00:00 [running]> on host b09a5d7d2d12
[2019-12-30 16:44:16,969] {taskinstance.py:1078} ERROR - 'dict object' has no attribute 'logoAnnotations'
Traceback (most recent call last):
  File "/opt/airflow/airflow/models/taskinstance.py", line 923, in _run_raw_task
    self.render_templates(context=context)
  File "/opt/airflow/airflow/models/taskinstance.py", line 1316, in render_templates
    self.task.render_template_fields(context)
  File "/opt/airflow/airflow/models/baseoperator.py", line 701, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/opt/airflow/airflow/models/baseoperator.py", line 710, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/opt/airflow/airflow/models/baseoperator.py", line 741, in render_template
    return jinja_env.from_string(content).render(**context)
  File "/usr/local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 411, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'logoAnnotations'
```

**Comment by turbaszek** [comment]
This problem occurred because the url of Google logo used as image to annotate returned 404.
