### ISSUE TITLE
TypeError: must be str, not int in CloudBaseHook

### ISSUE THREAD

**Issue by michalslowikowski00** [PolideaInternal/airflow#719]
`ERROR - Failed to execute task: must be str, not int.
Traceback (most recent call last):
  File "/opt/airflow/airflow/executors/debug_executor.py", line 80, in _run_task
    job_id=ti.job_id, **params
  File "/opt/airflow/airflow/utils/session.py", line 61, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/airflow/sentry.py", line 140, in wrapper
    return func(task_instance, *args, session=session, **kwargs)
  File "/opt/airflow/airflow/models/taskinstance.py", line 957, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/airflow/providers/google/marketing_platform/operators/analytics.py", line 66, in execute
    result = hook.list_accounts()
  File "/opt/airflow/airflow/providers/google/marketing_platform/hooks/analytics.py", line 69, in list_accounts
    .execute(num_retries=self.num_retries)
  File "/usr/local/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/googleapiclient/http.py", line 851, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/usr/local/lib/python3.6/site-packages/googleapiclient/http.py", line 153, in _retry_request
    for retry_num in range(num_retries + 1):
TypeError: must be str, not int`

[ ] Add tests
[ ] fix the method

**Comment by mik-laj** [comment]
@michalslowikowski00 Any progress? Do you need any support?

**Comment by michalslowikowski00** [comment]
Sorry, didn't have to look at this, but I would like to do this.

**Comment by michalslowikowski00** [comment]
But if it is important you can do it.

**Comment by turbaszek** [comment]
@michalslowikowski00 how one should replicate the error?

**Comment by mik-laj** [comment]
1. Set the environment variable according to the Airflow documentation - https://airflow.readthedocs.io/en/latest/howto/connection/gcp.html
```
export AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT='google-cloud-platform://?extra__google_cloud_platform__key_path=%2Fkeys%2Fkey.json&extra__google_cloud_platform__scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&extra__google_cloud_platform__project=airflow&extra__google_cloud_platform__num_retries=5'
```
2. Use any discovery based operator.
